
Если при запуске моделей dbt появляется ошибка такого рода как:

![cover](https://github.com/Malakhova-Natalya/Snippets/blob/main/dbt_error_Enum8/dbt%20-%20error%20Enum8.png)

проверьте, в каком терминале вы работаете - возможно, в powershell + у вас не включено облачное окружение Python?

Как избежать этой ошибки:

1. Заходим в Ubuntu
2. Активируем облачное окружение python

